/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerRole;

import Business.Customer.Customer;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Organization.Organization;

import Business.Role.CustomerRole;

import Business.UserAccount.UserAccount;
import Business.utils.CryptoSupport;
import Business.utils.ValidationUtils;
import java.awt.CardLayout;
import java.awt.Component;

import java.util.Date;
import javax.swing.JOptionPane;

import javax.swing.JPanel;
import userinterface.DoctorRole.DoctorWorkAreaJPanel;

/**
 *
 * @author raunak
 */
public class CustomerRegisterWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private EcoSystem system;
    private static final String secretKey = "9F2H65BYTJ";

    /**
     * Creates new form RequestLabTestJPanel
     */
    public CustomerRegisterWorkAreaJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        populateCombo();
    }

    private void populateCombo() {
        genderComboBox.removeAllItems();
        for (Customer.Gender type : Customer.Gender.values()) {
            genderComboBox.addItem(type);
        }
    }

    private void getValuesFromTextField(Customer customer) {
        if (userNameTextField.getText().isEmpty() || firstNameTextField.getText().isEmpty() || ageTextField.getText().isEmpty()
                || emailTextField.getText().isEmpty() || mobileNumberTextField.getText().isEmpty()
                || cityTextState.getText().isEmpty() || passwordTextField.getText().isEmpty()
                || reenterPasswordTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter all the fields");
        } else {
            try {
                if (ValidationUtils.validateNameAndNumber(userNameTextField.getText())) {
                    customer.setUserName(userNameTextField.getText());
                } else {
                    JOptionPane.showMessageDialog(this, "User name should have only aphabets and numbers");
                }
                if (ValidationUtils.validateFirstName(firstNameTextField.getText())) {
                    customer.setFirstName(firstNameTextField.getText());
                } else {
                    JOptionPane.showMessageDialog(this, "First name should only contain alphabets");
                }
                if (ValidationUtils.validateFirstName(lastNameTextField.getText())) {
                    customer.setLastName(lastNameTextField.getText());
                } else {
                    JOptionPane.showMessageDialog(this, "Last name should only contain alphabets");
                }
                customer.setAge(Integer.parseInt(ageTextField.getText()));
                if (ValidationUtils.validateEmail(emailTextField.getText())) {
                    customer.setEmail(CryptoSupport.encrypt(emailTextField.getText(), secretKey));
                } else {
                    JOptionPane.showMessageDialog(this, "Email should contain a valid email and not start with _");
                }
                customer.setCreateDate(new Date());

                customer.setMobileNumber(CryptoSupport.encrypt(mobileNumberTextField.getText(), secretKey));

                if (ValidationUtils.validateFirstName(cityTextState.getText())) {
                    customer.setCity(cityTextState.getText());
                } else {
                    JOptionPane.showMessageDialog(this, "City should only contain alphabets");
                }
                customer.setPassword(passwordTextField.getText());
                customer.setReenterPassword(reenterPasswordTextField.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Input not valid");
                return;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        userNameTextField = new javax.swing.JTextField();
        passwordTextField = new javax.swing.JTextField();
        registerBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        reenterPasswordTextField = new javax.swing.JTextField();
        firstNameTextField = new javax.swing.JTextField();
        lastNameTextField = new javax.swing.JTextField();
        ageTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        mobileNumberTextField = new javax.swing.JTextField();
        cityTextState = new javax.swing.JTextField();
        genderComboBox = new javax.swing.JComboBox();
        registerBtn1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel1.setText("User Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel2.setText("Password");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, -1, -1));

        userNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameTextFieldActionPerformed(evt);
            }
        });
        add(userNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 110, -1));
        add(passwordTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 110, -1));

        registerBtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        registerBtn.setText("Register");
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });
        add(registerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 580, -1, -1));
        add(registerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 610, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Welcome");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel4.setText("Re-enter password");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel5.setText("First Name");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel6.setText("Last Name");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel7.setText("Age");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel8.setText("Gender");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel9.setText("Email");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel10.setText("Mobile Number");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 490, -1, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel11.setText("City");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 540, -1, -1));
        add(reenterPasswordTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 100, -1));
        add(firstNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 110, -1));
        add(lastNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 110, -1));
        add(ageTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 110, -1));
        add(emailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 440, 110, -1));
        add(mobileNumberTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 490, 120, -1));
        add(cityTextState, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 540, 120, -1));

        genderComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(genderComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, -1, -1));

        registerBtn1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        registerBtn1.setText("<<Back");
        registerBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtn1ActionPerformed(evt);
            }
        });
        add(registerBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 580, -1, -1));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Image10.jpg"))); // NOI18N
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1950, 1040));
    }// </editor-fold>//GEN-END:initComponents

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        // TODO add your handling code here:
        CustomerRole customerRole = new CustomerRole();
        Customer customer = new Customer();
        getValuesFromTextField(customer);
        customerRole.setCustomer(customer);
        Employee employee = system.getEmployeeDirectory().createEmployee(customer.getFirstName(), customerRole);
        if(system.getUserAccountDirectory().checkIfUsernameIsUnique(customer.getUserName())) {
        UserAccount userAccount = system.getUserAccountDirectory().createUserAccount(customer.getUserName(), customer.getPassword(), employee, customerRole);
        } else {
            JOptionPane.showMessageDialog(this, "Username already exists");
        }
    }//GEN-LAST:event_registerBtnActionPerformed

    private void userNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameTextFieldActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_userNameTextFieldActionPerformed

    private void registerBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtn1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CustomerWorkAreaJPanel dwjp = (CustomerWorkAreaJPanel) component;
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_registerBtn1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageTextField;
    private javax.swing.JTextField cityTextState;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JComboBox genderComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JTextField mobileNumberTextField;
    private javax.swing.JTextField passwordTextField;
    private javax.swing.JTextField reenterPasswordTextField;
    private javax.swing.JButton registerBtn;
    private javax.swing.JButton registerBtn1;
    private javax.swing.JTextField userNameTextField;
    // End of variables declaration//GEN-END:variables
}
