/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerRole;

import userinterface.NurseRole.*;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author raunak
 */
public class OtpJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    String otp;
    /**
     * Creates new form ProcessWorkRequestJPanel
     */
    public OtpJPanel(JPanel userProcessContainer, String otp) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.otp = otp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        submitJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        otpTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setLayout(null);

        submitJButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        submitJButton.setText("Validate OTP");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });
        add(submitJButton);
        submitJButton.setBounds(540, 310, 175, 37);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("OTP");
        add(jLabel1);
        jLabel1.setBounds(460, 170, 50, 22);
        add(otpTextField);
        otpTextField.setBounds(590, 170, 140, 26);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/nurse4.jpg"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(4, 4, 1600, 750);
    }// </editor-fold>//GEN-END:initComponents

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
        if(validateOtp(otp)) {
            JOptionPane.showMessageDialog(this, "Correct OTP");
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CustomerWorkAreaJPanel dwjp = (CustomerWorkAreaJPanel) component;
        dwjp.validateOtp(true);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        } else {
            JOptionPane.showMessageDialog(this, "Incorrect OTP");
            userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CustomerWorkAreaJPanel dwjp = (CustomerWorkAreaJPanel) component;
        dwjp.validateOtp(false);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        }
    }//GEN-LAST:event_submitJButtonActionPerformed

    private boolean validateOtp(String otp) {
        if(otpTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Otp cannot be empty");
        }
        if(otpTextField.getText().equals(otp)) {
            return true;
        } else {
            return false;
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField otpTextField;
    private javax.swing.JButton submitJButton;
    // End of variables declaration//GEN-END:variables
}
